### PR TITLE
code => code.css to have syntax highlighting on github

### PR DESCRIPTION
**Pull request by Lightbulb8448**

### CODE REVIEW

**Comment by Lightbulb8448** [comment]
2nd commit is a little unrelated to 1st but they're both improvements

**Comment by AdelNorberg** [comment]
image
Once upon a time even I had a dark version, but that was 1+ years ago
(on the screen, the layout from the design is outdated)

**Comment by thetalkingcaat** [comment]
> image Once upon a time even I had a dark version, but that was 1+ years ago (on the screen, the layout from the design is outdated)

wow

**Comment by Lightbulb8448** [comment]
> image Once upon a time even I had a dark version, but that was 1+ years ago (on the screen, the layout from the design is outdated)

I found out yesterday that it existed when thetalkingcat said he'd make a dark mode css, and tried it out by changing the body element's class

**Comment by Lightbulb8448** [comment]
This has been fixed in other commits, I'll close

**Pull request closed without merging**
